### ISSUE TITLE
Mismatched dimensions

### ISSUE THREAD

**Issue by EtienneAumont** [CoBrALab/atlases#11]
Hi,

I'm trying to overlay the hippocampus label files on the T2 image using ITK-Snap on MacOS. However, the labels cannot be loaded because they are of a different size than the T2 main image. Eg. brain 1 is 523x631x540 while the labels are 489x734x734.

How can I load the labels on the T2?

Thanks - Étienne

**Comment by gdevenyi** [comment]
Hi,

The official release files are in MINC format and the MINC viewers don't care about this (Display and register).

You can reshape the T2 like the T1 with something like antsApplyTransforms (without a transform) for software which does not support generalized image display.

```
antsApplyTransforms -d 3 -i brain2_t2.nii.gz -r brain1_t1.nii.gz -o brain2_t2_reshape.nii.gz --verbose
```
