### ISSUE TITLE
Provide label_names files for processing with improved MAGET label_vols command

### ISSUE THREAD

**Issue by gdevenyi** [CoBrALab/atlases#2]
After implementing an improved label_vols in maget, it would be helpful to provide naming files to automate the header generation

**Comment by pipitone** [comment]
What does an "improved label_vols" look like?

**Comment by gdevenyi** [comment]
Doesn't exist yet, will include header generator :)

**Comment by pipitone** [comment]
> Doesn't exist yet, will include header generator :)

Headers for what?

**Comment by gdevenyi** [comment]
label_vols dumps a header consisting of "label number", if the atlas provides a mapping file (aka we generate one), we can use it so label_vols has names instead

**Comment by mallarchak** [comment]
I think we can likely insert a new field using minc_modify_header - may not
be a difficult process.

mallasr

**Comment by pipitone** [comment]
> I think we can likely insert a new field using minc_modify_header - may not
> be a difficult process.

Yes! I like that idea. Then a flag on label_vols to pull label names
from a referenced atlas.
